name: Random Thoughts
favicon: null
layout_spectrum: 0.25125
typography_spectrum: 0.96411
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f5ffff'
    - '#00001c'
    - '#0063db'
    - '#378eff'
    - '#79d9ff'
  brandStrength: 0.5
  lightness: 0.75
  saturation: 1
  rhythmicContrast: 0
purpose: []
