favicon: null
name: Random Thoughts
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0.1200717
  brandStrength: 0
  lightness: 1
  brandColors:
    - '#f5ffff'
    - '#00001c'
    - '#0063db'
    - '#378eff'
    - '#79d9ff'
  rhythmicContrast: 0
typography_spectrum: 0.96411
layout_spectrum: 0.4157706
analytics:
  twitter: null
  google: null
  facebook: null
cta:
  bucket: null
  version: null
  domain: null
